theme = "ananke"
baseURL = "https://fairwix.github.io/my-new-portfolio/"
languageCode = "ru-RU"
title = "Мой первый сайт на Hugo"

[params]
  mainSections = ["posts"]
  author = "Yuliya Smirnova"
  description = "Мой сайт на Hugo"
  background_color_class = "bg-dark-gray"
  featured_image = "/images/hero.jpg"

[[menu.main]]
name = "Главная"
url = "/"
weight = 1

[[menu.main]]
name = "Обо мне"
url = "/about/"
weight = 2

[[menu.main]]
name = "Контакты"
url = "/contact/"
weight = 3

[[menu.main]]
name = "HTTP Лаба"
url = "/http-lab/"
weight = 4
